import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Hire from "../components/Hire";
import Main from "../components/Main";
import People from "../components/People";
import Recruitment from "../components/Recruitment";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
      <Recruitment />
      <Hire />
      <People />
      <Footer />
    </div>
  );
}
